#!/bin/sh -e

dataset=$1
output=$2
workdir=$dataset/work

mkdir -p $dataset/aosp_system $workdir

# 1. Android 11 GSI (RP1A.200720.009)
URL=https://dl.google.com/developers/android/rvc/images/gsi/aosp_arm64-exp-RP1A.200720.009-6720564-019b517d.zip
echo "Pulling from $URL"
(cd $workdir && curl $URL | busybox unzip -)
sudo mount -t ext4 -oro,loop $workdir/system.img $dataset/aosp_system
rm -rf $workdir && mkdir -p $workdir
# 2. enwik8
URL=https://mattmahoney.net/dc/enwik8.zip
echo "Pulling from $URL"
(cd $workdir && curl $URL | busybox unzip -)
mv $workdir $dataset/enwik8 && mkdir -p $workdir
# 3. silesia
URL=https://mattmahoney.net/dc/silesia.zip
echo "Pulling from $URL"
(cd $workdir && curl $URL | busybox unzip -)
mv $workdir $dataset/silesia && mkdir -p $workdir
# 4. calgary
URL=https://mattmahoney.net/dc/calgary.zip
echo "Pulling from $URL"
(cd $workdir && curl $URL | busybox unzip -)
mv $workdir $dataset/calgary

shift 2
sudo bin/mkfs.erofs $@ $output $dataset
sudo chown $(id -u):$(id -g) $output
sudo umount $dataset/aosp_system
rm -rf $dataset
