name: stress

on:
    # schedule:
    #     - cron: "0 0,8,16 * * *"
    # Allows to run this workflow manually from the Actions tab
    workflow_dispatch:
        inputs:
            ko_repo:
                description: "Out-of-Tree FreeBSD Repository"
                default: "https://git.xdm.one/imrcpan/erofs-freebsd-out-tree.git"
                required: true
                type: string
            utils_repo:
                description: "erofs-utils Git Repository"
                default: "git://git.kernel.org/pub/scm/linux/kernel/git/xiang/erofs-utils.git"
                required: true
                type: string
            utils_branch:
                description: "erofs-utils Git Branch"
                default: "experimental"
                required: true
                type: string
            timeout:
                description: "Stress timeout"
                default: 7200
                required: true
                type: number
            stress-mkfs-options:
                description: "Customized mkfs options for stress testing"
                default: ""
                required: false
                type: string

env:
    LZ4_VER: 1.10.0
    XZ_VER: 5.6.4
    KO_REPO: ${{ github.event_name == 'schedule' && 'https://git.xdm.one/imrcpan/erofs-freebsd-out-tree.git' || github.event.inputs.ko_repo }}
    UTILS_REPO: ${{ github.event_name == 'schedule' && 'git://git.kernel.org/pub/scm/linux/kernel/git/xiang/erofs-utils.git' || github.event.inputs.utils_repo }}
    UTILS_BRANCH: ${{ github.event_name == 'schedule' && 'experimental' || github.event.inputs.utils_branch }}
    TIMEOUT: ${{ github.event_name == 'schedule' && 14400 || github.event.inputs.timeout }}

defaults:
    run:
        shell: bash

jobs:
    build-erofs-utils:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                suffix: ["", "_mt"]
        steps:
            - name: Checkout
              uses: actions/checkout@v7
            - name: Build erofs-utils
              run: |
                  sudo apt-get -qq update
                  sudo apt-get install -y autoconf automake libtool pkg-config libfuse-dev libselinux1-dev libzstd-dev uuid-dev
                  curl -L https://github.com/lz4/lz4/releases/download/v$LZ4_VER/lz4-$LZ4_VER.tar.gz | tar -zxv
                  (cd lz4-$LZ4_VER; make BUILD_STATIC=no; sudo make install BUILD_STATIC=no)
                  curl -L https://github.com/tukaani-project/xz/releases/download/v$XZ_VER/xz-$XZ_VER.tar.gz | tar -zxv
                  (cd xz-$XZ_VER; ./configure; sudo make install)
                  rm -rf erofs-utils; mkdir -p erofs-utils
                  git clone $UTILS_REPO -b $UTILS_BRANCH erofs-utils
                  cd erofs-utils
                  MT="dis";[ "x${{ matrix.suffix }}" = "x_mt" ] && MT="en"
                  mkdir output
                  ./autogen.sh && ./configure --enable-debug --enable-werror --enable-fuse \
                      --enable-lz4 --enable-lzma --with-selinux --with-libzstd \
                      --${MT}able-multithreading \
                      --prefix=$(pwd)/output && \
                      make && make install
                  cp -f contrib/stress output/bin
            - name: Upload erofs-utils
              uses: actions/upload-artifact@v7
              with:
                  name: erofs-utils${{ matrix.suffix }}
                  path: |
                      erofs-utils/output

    gen-golden-image:
        runs-on: ubuntu-latest
        needs: build-erofs-utils
        steps:
            - name: Checkout
              uses: actions/checkout@v7
            - name: Cache golden image
              id: cache-golden
              uses: actions/cache@v4
              with:
                  path: |
                      golden.erofs
                  key: golden-${{ hashFiles('./genimage') }}
            - name: Download erofs-utils prebuilts
              if: steps.cache-golden.outputs.cache-hit != 'true'
              uses: actions/download-artifact@v8
              with:
                  name: erofs-utils
            - name: Set up golden image
              if: steps.cache-golden.outputs.cache-hit != 'true'
              run: |
                  sudo apt-get -qq update
                  sudo apt-get install -y busybox
                  chmod +x ./*
                  chmod +x bin/mkfs.erofs bin/fsck.erofs bin/erofsfuse
                  ./genimage testdata golden.erofs '--xattr-inode-digest=sha256.erofs.fingerprint -zlz4hc,12 -Ededupe,fragments,ztailpacking -C65536'

    build-erofs-ko:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v7
            - name: Build EROFS
              uses: vmactions/freebsd-vm@v1
              with:
                  release: 15.1
                  envs: KO_REPO
                  cache-after-prepare: true
                  prepare: |

                  run: |
                      chmod +x ./*
                      ./build-erofs-ko
            - name: Upload KO
              uses: actions/upload-artifact@v7
              with:
                  name: erofs-ko
                  path: |
                      erofs.ko

    stress-run:
        runs-on: ubuntu-latest
        needs: [build-erofs-ko, build-erofs-utils, gen-golden-image]
        strategy:
            matrix:
                alg:
                    [
                        "",
                        "-zlz4",
                        "-zlz4hc,12",
                        "-zlzma,9",
                        "-zdeflate",
                        "-zzstd",
                    ]
                set: [0, 1]
                share: [0, 1]
        steps:
            - name: Checkout
              uses: actions/checkout@v7
            - name: Restore rootfs image
              id: restore-rootfs
              uses: actions/cache/restore@v4
              with:
                  path: |
                      rootfs.img
                  key: stressrootfs-${{hashFiles('stress-overlay', 'genrootfs')}}
            - name: Fetch golden image
              id: fetch-golden
              uses: actions/cache@v4
              with:
                  path: |
                      golden.erofs
                  key: golden-${{ hashFiles('./genimage') }}
            - name: Download erofs-utils prebuilts
              uses: actions/download-artifact@v8
              with:
                  name: erofs-utils
            - name: Download KO
              uses: actions/download-artifact@v8
              with:
                  name: erofs-ko
            - name: Stress prepare
              run: |
                  sudo apt-get update -qq
                  sudo apt-get install -y fuse
                  chmod +x ./*
                  chmod +x bin/mkfs.erofs bin/fsck.erofs bin/erofsfuse
                  mkdir mnt
                  bin/erofsfuse golden.erofs mnt
                  if [ "x${{ matrix.set }}" = "x1" ]; then
                    if [ "x${{ matrix.alg }}" = "x" ]; then
                      MKFS_OPTIONS="-Ededupe"
                    else
                      MKFS_OPTIONS="${{ github.event.inputs.stress-mkfs-options }}"
                      [ "x$MKFS_OPTIONS" = "x" ] && MKFS_OPTIONS="-Ededupe,fragments,ztailpacking"
                    fi
                  else
                      MKFS_OPTIONS=""
                  fi
                  seed=$((RANDOM * RANDOM))
                  echo "random seed: $seed"
                  if [ "x${{ matrix.share }}" = "x1" ]; then
                    bin/mkfs.erofs ${{ matrix.alg }} $MKFS_OPTIONS --xattr-inode-digest=sha256.erofs.fingerprint testA.erofs mnt
                    bin/mkfs.erofs --xattr-inode-digest=sha256.erofs.fingerprint testB.erofs mnt
                    fusermount -u mnt; rm -rf mnt
                    ./stress-arg-create $TIMEOUT $seed ${{ matrix.share }}
                  else
                    bin/mkfs.erofs ${{ matrix.alg }} $MKFS_OPTIONS testA.erofs mnt
                    fusermount -u mnt; rm -rf mnt
                    ./stress-arg-create $TIMEOUT $seed ${{ matrix.share }}
                  fi
            - name: Stress run
              uses: vmactions/freebsd-vm@v1
              with:
                  release: 15.1
                  cache-after-prepare: true
                  prepare: |

                  run: |
                      chmod +x ./*
                      ./stress-run
            - name: Upload images if the test fails
              uses: actions/upload-artifact@v7
              if: failure()
              with:
                  name: qemu-image-dump-${{ matrix.alg }}-${{ matrix.set }}-${{ matrix.share }}
                  path: |
                      *.erofs
                      baddump*
                      !overlay.ext4
